name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.3

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  octo_image: ^1.0.2
  cached_network_image_web:
    git:
      url: https://github.com/BensonGicheru/flutter_cached_network_image.git
      path: cached_network_image_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_lints: ^1.0.4
  file: ^6.1.0

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'
